### PR TITLE
Casing namespace

### LINKED ISSUE #144: Casing in namespace is not respected
In https://github.com/rescript-lang/experimental-rescript-webapi I noticed that `bunx rewatch` has slightly different output than `bunx rescript`.

Steps to reproduce:

- Create new project with `rescript@12.0.0-alpha.4`
- Add `"namespace": "PkmnAPI",` to `rescript.json`
- Create a function in one file and use it in another

`ProduceAPI.res`

```res
let meh = (a: int) => {
  true
}
```

`Consume.res`

```res
let b  = ProduceAPI.meh(1);
```

After `bunx rescript` I get:

```js
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ProduceAPI$PkmnAPI from "./ProduceAPI.re.js";

let b = ProduceAPI$PkmnAPI.meh(1);

export {
  b,
}
/* b Not a pure module */
```

with `bunx rewatch`:

```res
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ProduceAPI$PkmnApi from "./ProduceAPI.re.js";

let b = ProduceAPI$PkmnApi.meh(1);

export {
  b,
}
/* b Not a pure module */
```

`ProduceAPI$PkmnAPI` (rescript) versus `ProduceAPI$PkmnApi` (rewatch)

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #144 

I have very little idea what I'm doing here.
I don't know any Rust and just tried the hint of @tsnobip in https://github.com/rescript-lang/rewatch/issues/144#issuecomment-2507689911

### CODE REVIEW

File: src/config.rs [hunk 1]
```diff
@@ -312,7 +333,7 @@ impl Config {
                 namespace if namespace.is_case(Case::UpperFlat) => {
                     packages::Namespace::Namespace(namespace.to_string())
                 }
-                namespace => packages::Namespace::Namespace(namespace.to_string().to_case(Case::Pascal)),
+                namespace => packages::Namespace::Namespace(namespace_from_package_name(namespace)),
```
Comment (tsnobip) [inline src/config.rs:336]: There is another use of `to_case(Case::Pascal)` on line 348, but actually I think you can simplify this match quite a lot and always process namespace whatever the initial case with this new function.

**Comment by jfrolich** [comment]
This is amazing, can we merge this?

**Comment by nojaf** [comment]
Can't fix CI this week. Feel free to tweak this if you have the bandwidth.

**Review by jfrolich — APPROVED** [review]
